version: '3.8'

services:
  org-social-preview:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./social.org:/app/social.org:ro
      - ./template.html:/app/template.html:ro
      - ./preview:/app/preview
    environment:
      - SOCIAL_FILE=/app/social.org
      - PREVIEW_DIR=/app/preview
      - TEMPLATE_DIR=/app
      - TEMPLATE_NAME=template.html
